import type { Player, Match } from "./types";

export const MOCK_PLAYERS: Player[] = [
  {
    id: "hossam-hassan",
    name: "Hossam Hassan",
    birthYear: 1966,
    birthCity: "Kafr El Sheikh",
    caps: 184,
    goals: 69,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "",
    transfermarktUrl: "",
    fullName: "",
    nickname: "",
    clubs: [
      { clubName: "Al Ahly", clubCountry: "Egypt", yearsActive: "1984–1992" },
      { clubName: "Zamalek", clubCountry: "Egypt", yearsActive: "1992–2001" },
    ],
  },
  {
    id: "ahmed-hassan",
    name: "Ahmed Hassan",
    birthYear: 1975,
    birthCity: "Kafr El Sheikh",
    caps: 184,
    goals: 12,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "",
    transfermarktUrl: "",
    fullName: "",
    nickname: "",
    clubs: [
      { clubName: "Zamalek", clubCountry: "Egypt", yearsActive: "1993–2000" },
      { clubName: "Beşiktaş", clubCountry: "Turkey", yearsActive: "2000–2005" },
      { clubName: "Al Ahly", clubCountry: "Egypt", yearsActive: "2005–2012" },
    ],
  },
  {
    id: "essam-el-hadary",
    name: "Essam El-Hadary",
    birthYear: 1973,
    birthCity: "Damietta",
    caps: 169,
    goals: 0,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "",
    transfermarktUrl: "",
    fullName: "",
    nickname: "",
    clubs: [
      { clubName: "Al Ahly", clubCountry: "Egypt", yearsActive: "1993–2010" },
    ],
  },
  {
    id: "ahmed-fathy",
    name: "Ahmed Fathy",
    birthYear: 1984,
    birthCity: "Port Said",
    caps: 105,
    goals: 3,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "",
    transfermarktUrl: "",
    fullName: "",
    nickname: "",
    clubs: [
      { clubName: "Al Ahly", clubCountry: "Egypt", yearsActive: "2010–2019" },
    ],
  },
  {
    id: "mohamed-salah",
    name: "Mohamed Salah",
    birthYear: 1992,
    birthCity: "Nagrig",
    caps: 103,
    goals: 71,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Mohamed_Salah_2018.jpg/220px-Mohamed_Salah_2018.jpg",
    transfermarktUrl: "https://www.transfermarkt.com/mohamed-salah/profil/spieler/148455",
    fullName: "",
    nickname: "",
    clubs: [
      { clubName: "Liverpool", clubCountry: "England", yearsActive: "2017–2025" },
    ],
  },
  {
    id: "wael-gomaa",
    name: "Wael Gomaa",
    birthYear: 1981,
    birthCity: "Cairo",
    caps: 69,
    goals: 2,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "",
    transfermarktUrl: "",
    fullName: "",
    nickname: "",
    clubs: [{ clubName: "Al Ahly", clubCountry: "Egypt", yearsActive: "2000–2012" }],
  },
  {
    id: "amr-zaki",
    name: "Amr Zaki",
    birthYear: 1983,
    birthCity: "Damietta",
    caps: 56,
    goals: 26,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "",
    transfermarktUrl: "",
    fullName: "",
    nickname: "",
    clubs: [
      { clubName: "Zamalek", clubCountry: "Egypt", yearsActive: "2002–2007" },
      { clubName: "Wigan Athletic", clubCountry: "England", yearsActive: "2007–2009" },
    ],
  },
  {
    id: "hossam-ghaly",
    name: "Hossam Ghaly",
    birthYear: 1981,
    birthCity: "Mansoura",
    caps: 60,
    goals: 3,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "",
    transfermarktUrl: "",
    fullName: "",
    nickname: "",
    clubs: [
      { clubName: "Al Ahly", clubCountry: "Egypt", yearsActive: "2000–2007" },
      { clubName: "Tottenham Hotspur", clubCountry: "England", yearsActive: "2006–2009" },
    ],
  },
  {
    id: "mohamed-aboutrika",
    name: "Mohamed Aboutrika",
    birthYear: 1978,
    birthCity: "Cairo",
    caps: 101,
    goals: 41,
    primaryCountry: "Egypt",
    countries: ["Egypt"],
    photoUrl: "",
    transfermarktUrl: "",
    fullName: "",
    nickname: "",
    clubs: [{ clubName: "Al Ahly", clubCountry: "Egypt", yearsActive: "2000–2013" }],
  },
];

// Matches include empty lineup/subs since mock data predates that feature
const NO_LINEUP = { gk: [], defenders: [], midfielders: [], attackers: [], subs: [], lineup: [] };

export const MOCK_MATCHES: Match[] = [
  { id: "1920-08-28-italy",        date: "1920-08-28", opponent: "Italy",        egyptGoals: 1, opponentGoals: 4, competition: "Olympics 1920",         venue: "Stade Olympique d'Anvers",    city: "Antwerp",       isHome: false, ...NO_LINEUP },
  { id: "1934-05-27-hungary",      date: "1934-05-27", opponent: "Hungary",      egyptGoals: 2, opponentGoals: 4, competition: "FIFA World Cup 1934",    venue: "Stadio Nazionale del PNF",    city: "Rome",          isHome: false, ...NO_LINEUP },
  { id: "1957-02-16-ethiopia",     date: "1957-02-16", opponent: "Ethiopia",     egyptGoals: 4, opponentGoals: 0, competition: "AFCON 1957 Final",       venue: "Municipal Stadium",           city: "Khartoum",      isHome: false, ...NO_LINEUP },
  { id: "1986-03-13-cameroon",     date: "1986-03-13", opponent: "Cameroon",     egyptGoals: 0, opponentGoals: 0, competition: "AFCON 1986 Final",       venue: "Cairo International Stadium", city: "Cairo",         isHome: true,  ...NO_LINEUP },
  { id: "1998-02-28-south-africa", date: "1998-02-28", opponent: "South Africa", egyptGoals: 2, opponentGoals: 0, competition: "AFCON 1998 Final",       venue: "Ouagadougou Stadium",         city: "Ouagadougou",   isHome: false, ...NO_LINEUP },
  { id: "2006-02-10-ivory-coast",  date: "2006-02-10", opponent: "Ivory Coast",  egyptGoals: 0, opponentGoals: 0, competition: "AFCON 2006 Final",       venue: "Cairo International Stadium", city: "Cairo",         isHome: true,  ...NO_LINEUP },
  { id: "2008-02-10-cameroon",     date: "2008-02-10", opponent: "Cameroon",     egyptGoals: 1, opponentGoals: 0, competition: "AFCON 2008 Final",       venue: "Estadio Nacional de Ghana",   city: "Accra",         isHome: false, ...NO_LINEUP },
  { id: "2010-01-31-ghana",        date: "2010-01-31", opponent: "Ghana",        egyptGoals: 1, opponentGoals: 0, competition: "AFCON 2010 Final",       venue: "Estadio de Bata",             city: "Bata",          isHome: false, ...NO_LINEUP },
  { id: "2018-06-15-uruguay",      date: "2018-06-15", opponent: "Uruguay",      egyptGoals: 0, opponentGoals: 1, competition: "FIFA World Cup 2018",    venue: "Ekaterinburg Arena",          city: "Yekaterinburg", isHome: false, ...NO_LINEUP },
  { id: "2018-06-19-russia",       date: "2018-06-19", opponent: "Russia",       egyptGoals: 1, opponentGoals: 3, competition: "FIFA World Cup 2018",    venue: "Saint Petersburg Stadium",    city: "St Petersburg", isHome: false, ...NO_LINEUP },
  { id: "2018-06-25-saudi-arabia", date: "2018-06-25", opponent: "Saudi Arabia", egyptGoals: 2, opponentGoals: 2, competition: "FIFA World Cup 2018",    venue: "Volgograd Arena",             city: "Volgograd",     isHome: false, ...NO_LINEUP },
  { id: "2022-01-11-nigeria",      date: "2022-01-11", opponent: "Nigeria",      egyptGoals: 1, opponentGoals: 0, competition: "AFCON 2021",             venue: "Stade Roumde Adjia",          city: "Garoua",        isHome: false, ...NO_LINEUP },
  { id: "2022-02-06-senegal",      date: "2022-02-06", opponent: "Senegal",      egyptGoals: 0, opponentGoals: 0, competition: "AFCON 2021 Final",       venue: "Stade d'Olembe",             city: "Yaoundé",       isHome: false, ...NO_LINEUP },
  { id: "2025-06-20-morocco",      date: "2025-06-20", opponent: "Morocco",      egyptGoals: 1, opponentGoals: 2, competition: "WCQ 2026",               venue: "Cairo International Stadium", city: "Cairo",         isHome: true,  ...NO_LINEUP },
  { id: "2025-09-09-sierra-leone", date: "2025-09-09", opponent: "Sierra Leone", egyptGoals: 3, opponentGoals: 0, competition: "WCQ 2026",               venue: "Cairo International Stadium", city: "Cairo",         isHome: true,  ...NO_LINEUP },
];

export const mockSheetData: Record<string, Record<string, string>[]> = {
  matches: MOCK_MATCHES.map((m) => ({
    date: m.date,
    opponent: m.opponent,
    egyptGoals: String(m.egyptGoals),
    opponentGoals: String(m.opponentGoals),
    competition: m.competition,
    venue: m.venue,
    city: m.city,
    isHome: String(m.isHome),
    gk: "",
    defenders: "",
    midfielders: "",
    attackers: "",
    subs: "",
  })),
  Players: MOCK_PLAYERS.map((p) => ({
    playerName: p.name,
    playerBirthYear: String(p.birthYear),
    playerBirthCity: p.birthCity,
    playerCountries: p.countries.join(", "),
    playerClubs: p.clubs.map((c) => c.clubName).join(", "),
    playerCaps: String(p.caps),
    playerGoals: String(p.goals),
    photoUrl: p.photoUrl,
    transfermarktUrl: p.transfermarktUrl,
    playerFullName: p.fullName,
    nickname: p.nickname,
  })),
};
